# Generated by Django 3.1.1 on 2020-10-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0040_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='password', max_length=128),
            preserve_default=False,
        ),
    ]
