# Generated by Django 3.1.1 on 2020-10-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0041_patient_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email_info',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
