# Generated by Django 3.1.1 on 2020-10-30 02:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0042_auto_20201027_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('visit_rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('visit_notes', models.CharField(max_length=1000)),
                ('team_rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('team_notes', models.CharField(max_length=1000)),
                ('misc_notes', models.CharField(max_length=1000)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_order', to='xamine.order')),
            ],
        ),
    ]
