# Generated by Django 3.1.1 on 2020-10-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0043_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='misc_notes',
        ),
        migrations.AlterField(
            model_name='survey',
            name='team_notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='visit_notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
