# Generated by Django 3.1.1 on 2020-10-31 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0045_order_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_survey', to='xamine.survey'),
        ),
    ]
