# Generated by Django 3.1.2 on 2020-11-04 22:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0046_auto_20201031_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mon_hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)])),
                ('tues_hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)])),
                ('thur_hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)])),
                ('fri_hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)])),
                ('sat_hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)])),
                ('sun_hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_of', models.DateField(blank=True, null=True)),
                ('time_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_cat', to='xamine.timecategory')),
            ],
        ),
    ]
