# Generated by Django 3.1.2 on 2020-11-05 02:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0047_timecategory_weeklyhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecategory',
            name='wed_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
