# Generated by Django 3.1.2 on 2020-11-05 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xamine', '0049_remove_weeklyhours_time_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecategory',
            name='week',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='week', to='xamine.weeklyhours'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyhours',
            name='employee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='auth.user'),
            preserve_default=False,
        ),
    ]
