# Generated by Django 3.1.2 on 2020-11-11 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0053_order_receptionist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_survey', to='xamine.survey'),
        ),
    ]
